### ISSUE TITLE
Closeness within subgraphs

### ISSUE THREAD

**Issue by giovannivolpe** [TheoBerglin/TutorialGIT#45]
Once pathlength_within_subgraphs is implemented, implementation of:

- [ ] closeness_within_subgraphs + test
- [ ] closeness_in_within_subgraphs + test
- [ ] closeness_out_within_subgraphs + test

**Comment by AdamLiberda** [comment]
As we discussed in regards to issue #35 the pathlength calculations take subgraphs into consideration. So if a node is disconnected from a subgraph, this node is not included when the pathlength is calculated. Unless we want to change/add the implementation to include this node (and return pl=inf), i'd say this issue is already handled. What do you think?

**Comment by giovannivolpe** [comment]
Yes, it makes sense

**Comment by AdamLiberda** [comment]
Closing
