### ISSUE TITLE
Participation measure

### ISSUE THREAD

**Issue by AdamLiberda** [TheoBerglin/TutorialGIT#61]
The participation coefficient shows the node connectivity through the available communities. It is expressed by the ratio of the edges that a node forms within a community to the total number of edges the node forms within the whole graph. Needs the structure() method.

- [x] Create test function for participation-in
- [x] Implement measure for participation-in
- [x] Create test function for participation-out
- [x] Implement measure for participation-out
- [x] Create test function for participation
- [x] Implement measure for participation

**Comment by AdamLiberda** [comment]
For this function we need an additional argument: structure.

**Comment by AdamLiberda** [comment]
I'm thinking we might need to implement in-participation and participation as well? Cause right now we check out-edges so basically we have out-participation if i didn't misinterpret. So we could check in-edges and thereby have in-participation and then add participation by defining it in a clever way (a mean of in/out ?). @mitemijalkov @giovannivolpe

**Comment by mitemijalkov** [comment]
I quickly checked online and you are right. The participation can be defined based on both out and in degrees of the nodes, therefore seems that we need to add the in degree one as well.
However, I think that in general the participation coefficient will not be the mean of the in and out ones. The reason is that to calculate it we only consider the edges between nodes within the same module. So there might be a situation for a given node that maybe it makes lots of in-connections within module but lots of out-connections with nodes in different modules. In this situation, the calculating the participation as the mean would not be correct.

**Comment by AdamLiberda** [comment]
I've implemented both in-and out-participation now. I'm wondering whether an overall participation is actually needed. Would it actually provide any relevant information? I've searched in some literature and online and couldn't find anything.

**Comment by mitemijalkov** [comment]
The way I see this, an overall participation (basically without distinguishing in or out) would be mostly used for the undirected network. Then, if an user wants to calculate in and out separately for directed network he could do it also. I believe that the overall participation needs to be implemented separately due to the fact that it cannot be defined simply as a mean from the in and out versions.
I would think that this is very analogous to the degree calculations. Even though we have in and out degree, we basically want also a degree function without explicit reference to direction.

**Comment by AdamLiberda** [comment]
Okay, i think i agree. But in that case a measure called participation would only be callable for undirected networks and in this case (for undirected networks) participation-in gives the same results as participation-out. Therefore the participation measure would basically just check if the graph is undirected and, if yes, call participation-in (or -out) and if no, raise an error. Do you agree?

**Comment by mitemijalkov** [comment]
That is for sure one way to do it. The alternative would be that if a graph is directed and partitition measure is requested, we first symmetrize the matrix and then calculate it for that graph. If the in or out is requested then we calculate it in the original graph. Maybe we can get the input from @giovannivolpe and we can make a decision accordingly.
